version : "3"
services:
  scheduler-web:
    build:
      context: .
      dockerfile: dockerfiles/Web.Dockerfile
    container_name: scheduler-web
    depends_on:
      - scheduler-pg
    volumes:
      - ./:/var/www/html
    restart: always
    ports:
      - "2314:80"
    environment:
      APP_NAME: 'Scheduler'
      XDEBUG_CONFIG: "mode=debug,coverage,develop client_host=host.docker.internal discover_client_host=1 start_with_request=yes"
    networks:
      scheduler-network:
        ipv4_address: 23.214.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  scheduler-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    container_name: scheduler-pg
    volumes:
      - scheduler-pg-disk:/var/lib/postgres
    networks:
      scheduler-network:
        ipv4_address: 23.214.1.2

  scheduler-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: scheduler-q
    depends_on:
      - scheduler-web
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    networks:
      scheduler-network:
        ipv4_address: 23.214.1.3

  scheduler-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: scheduler-mailpit
    restart: always
    networks:
      scheduler-network:
        ipv4_address: 23.214.1.4

  scheduler-0x:
    build:
      context: .
      dockerfile: dockerfiles/SansXdebug.Dockerfile
    container_name: scheduler-0x
    depends_on:
      - scheduler-web
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      scheduler-network:
        ipv4_address: 23.214.1.5

  scheduler-fe:
    build:
      context: .
      dockerfile: dockerfiles/Fe.Dockerfile
    container_name: scheduler-fe
    depends_on:
      - scheduler-web
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    networks:
      scheduler-network:
        ipv4_address: 23.214.1.6

# On-disk storage of DB data, when containers are stopped/removed
volumes:
  scheduler-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  scheduler-network:
    ipam:
      driver: default
      config:
        - subnet: 23.214.0.0/16
