name: CoIn

on:
  push:
    paths:
      - '**/.php'
      - '**/.yml'
      - '.github/**/.yml'
      - '**/.yaml'
      - '**/.json'
      - '.env.*'
      - 'terraform/**'

jobs:
  CoIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose
        run: docker-compose up -d
      - name: Check PHP version
        run: docker-compose exec -T scheduler-web php -v
      - name: Composer install [ + npm install && npm run build]
        run: docker-compose exec -T scheduler-web composer clearcache && composer install --no-interaction --no-progress --no-suggest --prefer-dist
      - name: CI checks
        run: docker-compose exec -T scheduler-web composer run ci

